<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>WinFormsExampleApp</RootNamespace>
    <AssemblyName>WinFormsExampleApp</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
