<Project>
  <Target Name="PrepareDeepFlowTestPayloadLayout" AfterTargets="Build">
    <ItemGroup>
      <_DeepFlowPayload Include="$(ArtifactsStagingRoot)payloads\**\*.*" />
      <_DeepFlowResource Include="$(ArtifactsStagingRoot)DeepFlowTestResources\**\*.dll;$(ArtifactsStagingRoot)DeepFlowTestResources\**\*.exe;$(ArtifactsStagingRoot)DeepFlowTestResources\**\*.config;$(ArtifactsStagingRoot)DeepFlowTestResources\**\*.pdb" />
    </ItemGroup>
    <Copy SourceFiles="@(_DeepFlowPayload)" DestinationFiles="@(_DeepFlowPayload->'$(OutDir)payloads\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(_DeepFlowResource)" DestinationFiles="@(_DeepFlowResource->'$(OutDir)DeepFlowTestResources\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>

  <Target Name="PrepareDeepFlowTestPayloadPublishLayout" AfterTargets="Publish">
    <ItemGroup>
      <_DeepFlowPublishPayload Include="$(ArtifactsStagingRoot)payloads\**\*.*" />
      <_DeepFlowPublishResource Include="$(ArtifactsStagingRoot)DeepFlowTestResources\**\*.dll;$(ArtifactsStagingRoot)DeepFlowTestResources\**\*.exe;$(ArtifactsStagingRoot)DeepFlowTestResources\**\*.config;$(ArtifactsStagingRoot)DeepFlowTestResources\**\*.pdb" />
    </ItemGroup>
    <Copy SourceFiles="@(_DeepFlowPublishPayload)" DestinationFiles="@(_DeepFlowPublishPayload->'$(PublishDir)payloads\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(_DeepFlowPublishResource)" DestinationFiles="@(_DeepFlowPublishResource->'$(PublishDir)DeepFlowTestResources\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
