<Project>
  <Import Project="..\Directory.Build.props" />

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputPath>$(MSBuildThisFileDirectory)bin\$(MSBuildProjectName)\$(Configuration)\</OutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)output\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
</Project>
