<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>DeepFlowTest.Tests</RootNamespace>
    <AssemblyName>DeepFlowTest.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <DefineConstants>$(DefineConstants);DEEPFLOWTEST_INJECTOR_TESTS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <ProjectReference Include="..\DeepFlowTest\DeepFlowTest.csproj" />
    <ProjectReference Include="..\DeepFlowTest.Recorder\DeepFlowTest.Recorder.csproj" />
    <ProjectReference Include="..\TestHarnesses\HelloWorld\HelloWorld.csproj" />
  </ItemGroup>

  <ItemGroup>
    <RuntimeHostConfigurationOption Include="Switch.System.Windows.Media.ShouldNotRenderInNonInteractiveWindowStation" Value="false" />
    <RuntimeHostConfigurationOption Include="Switch.System.Windows.Media.ShouldRenderEvenWhenNoDisplayDevicesAreAvailable" Value="true" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\InjectorData.cs" Link="Linked\Shared\InjectorData.cs" />
    <Compile Include="..\DeepFlowTest.InjectorLauncher\*.cs" Link="Linked\InjectorLauncher\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
